@extends('reports.layout', ['title' => 'Reporte de Propiedades Más Consultadas'])
@section('content')
<h2>Resumen</h2><table><tr><th>Total de visualizaciones</th></tr><tr><td>{{ $data['resumen']['total_visualizaciones'] }}</td></tr></table>
<h2>Top consultadas</h2><table><tr><th>Inmueble</th><th>Zona</th><th>Precio</th><th>Visualizaciones</th><th>Días publicado</th></tr>@foreach($data['tablas']['top_consultadas'] as $row)<tr><td>{{ $row['codigo'] }} — {{ $row['titulo'] }}</td><td>{{ $row['zona'] }}</td><td>{{ number_format($row['precio'], 2) }}</td><td>{{ $row['visualizaciones'] }}</td><td>{{ $row['dias_publicado'] }}</td></tr>@endforeach</table>
<h2>Bottom consultadas</h2><table><tr><th>Inmueble</th><th>Zona</th><th>Visualizaciones</th></tr>@foreach($data['tablas']['bottom_consultadas'] as $row)<tr><td>{{ $row['codigo'] }} — {{ $row['titulo'] }}</td><td>{{ $row['zona'] }}</td><td>{{ $row['visualizaciones'] }}</td></tr>@endforeach</table>
<h2>Promedios</h2><table><tr><th>Categoría</th><th>Promedio</th><th>Zona</th><th>Promedio</th></tr>@php($max = max(count($data['graficas']['promedio_visualizaciones_por_categoria']), count($data['graficas']['promedio_visualizaciones_por_zona'])))@for($i=0; $i<$max; $i++)<tr><td>{{ $data['graficas']['promedio_visualizaciones_por_categoria'][$i]['categoria'] ?? '' }}</td><td>{{ $data['graficas']['promedio_visualizaciones_por_categoria'][$i]['promedio_visualizaciones'] ?? '' }}</td><td>{{ $data['graficas']['promedio_visualizaciones_por_zona'][$i]['zona'] ?? '' }}</td><td>{{ $data['graficas']['promedio_visualizaciones_por_zona'][$i]['promedio_visualizaciones'] ?? '' }}</td></tr>@endfor</table>
<h2>Antigüedad vs consultas</h2><table><tr><th>Rango</th><th>Inmuebles</th><th>Visualizaciones</th><th>Promedio</th></tr>@foreach($data['tablas']['antiguedad_vs_consultas']['por_banda'] as $row)<tr><td>{{ $row['rango'] }}</td><td>{{ $row['total_inmuebles'] }}</td><td>{{ $row['total_visualizaciones'] }}</td><td>{{ $row['promedio_visualizaciones'] }}</td></tr>@endforeach</table>
@if($data['resumen']['total_visualizaciones'] === 0)<p class="muted">Sin datos para los filtros seleccionados.</p>@endif
@endsection
